# Generated by Django 4.0 on 2023-04-18 09:02

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='Район')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('house', models.CharField(max_length=255, verbose_name='Дом')),
                ('office', models.CharField(blank=True, max_length=255, null=True, verbose_name='Офис')),
                ('floor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Этаж')),
                ('extra_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='MasterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Рейтинг')),
                ('uuid', models.PositiveIntegerField(default=0, unique=True, verbose_name='UUID')),
                ('active_subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.activesubscriptions', verbose_name='Активная подписка')),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.locations', verbose_name='Адрес')),
                ('specializations', models.ManyToManyField(blank=True, to='services.Specializations', verbose_name='Специализации')),
            ],
            options={
                'verbose_name': 'Информация мастера',
                'verbose_name_plural': 'Информации мастеров',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30, verbose_name='Роль')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('sex', models.CharField(max_length=30, verbose_name='Пол')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото профиля')),
                ('status', models.CharField(default='Active 🟢', max_length=100, verbose_name='Статус')),
                ('master_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.masterinfo')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_theme', models.CharField(default='LIGHT', max_length=255, verbose_name='Цветовая тема')),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
        migrations.CreateModel(
            name='VerificationCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('code', models.PositiveIntegerField(unique=True, verbose_name='Код')),
                ('expiration_time', models.DateTimeField(default=users.models.get_code_expiration_time, editable=False, verbose_name='Время истечения')),
            ],
            options={
                'verbose_name': 'Код для проверки',
                'verbose_name_plural': 'Коды для проверки',
            },
        ),
        migrations.CreateModel(
            name='UsersPhonesNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Номер телефона пользователя',
                'verbose_name_plural': 'Номера телефонов пользователей',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usersettings'),
        ),
        migrations.CreateModel(
            name='UnregisteredClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masterinfo', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Незарегистрированный клиент',
                'verbose_name_plural': 'Незарегистрированные клиенты',
            },
        ),
    ]
