# Generated by Django 4.0 on 2023-03-12 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_theme', models.CharField(max_length=255, verbose_name='Цветовая тема')),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.usersettings'),
        ),
    ]
