# Generated by Django 4.0 on 2023-04-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterinfo',
            name='active_subscription',
        ),
    ]
