# Generated by Django 4.0 on 2023-03-12 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0002_usersettings_users_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='Местоположение')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Рейтинг')),
                ('specializations', models.ManyToManyField(blank=True, to='services.Specializations')),
            ],
            options={
                'verbose_name': 'Информация мастера',
                'verbose_name_plural': 'Информации мастеров',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='master_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.masterinfo'),
        ),
    ]
