# Generated by Django 4.0 on 2023-07-11 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_verificationcodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='color_theme',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notification_status',
            field=models.BooleanField(default=True, verbose_name='отправлять уведомления'),
        ),
        migrations.CreateModel(
            name='NotificationTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='Токен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Токен для пуш уведомлений',
                'verbose_name_plural': 'Токены для пуш уведомлений',
            },
        ),
    ]
