# Generated by Django 4.0 on 2023-04-24 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_masterinfo_active_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unregisteredclients',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.masterinfo', verbose_name='Мастер'),
        ),
    ]
