# Generated by Django 4.0 on 2023-03-15 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_masterinfo_users_master_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersPhonesNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Номер телефона пользователя',
                'verbose_name_plural': 'Номера телефонов пользователей',
            },
        ),
        migrations.CreateModel(
            name='UsersImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Изображение пользователя',
                'verbose_name_plural': 'Изображения пользователей',
            },
        ),
        migrations.CreateModel(
            name='UnregisteredClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masterinfo', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Незарегистрированный клиент',
                'verbose_name_plural': 'Незарегистрированные клиенты',
            },
        ),
    ]
