# Generated by Django 4.0 on 2023-04-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_unregisteredclients_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='unregisteredclients',
            name='extra_info',
            field=models.TextField(default='asd', verbose_name='Дополнительная информация'),
            preserve_default=False,
        ),
    ]
