# Generated by Django 4.0 on 2023-07-12 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_usersettings_color_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterinfo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='unregisteredclients',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masterinfo', verbose_name='Мастер'),
        ),
    ]
