# Generated by Django 4.0 on 2023-04-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_unregisteredclients_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unregisteredclients',
            name='extra_info',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
    ]
