# Generated by Django 4.0 on 2023-03-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_users_email_alter_users_master_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersImages',
        ),
    ]
