# Generated by Django 4.0 on 2023-03-23 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('users', '0006_delete_usersimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterinfo',
            name='active_subscription',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.activesubscriptions'),
            preserve_default=False,
        ),
    ]
