# Generated by Django 4.0 on 2023-03-24 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscriptions_type'),
        ('services', '0003_alter_services_name_serviceimages'),
        ('users', '0007_masterinfo_active_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterinfo',
            name='active_subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.activesubscriptions', verbose_name='Активная подписка'),
        ),
        migrations.AlterField(
            model_name='masterinfo',
            name='location',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='masterinfo',
            name='specializations',
            field=models.ManyToManyField(blank=True, to='services.Specializations', verbose_name='Специализации'),
        ),
    ]
