# Generated by Django 4.0 on 2023-03-26 01:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_masterinfo_active_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterinfo',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
