# Generated by Django 4.0 on 2023-03-26 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscriptions_type'),
        ('users', '0009_masterinfo_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='masterinfo',
            name='active_subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.activesubscriptions', verbose_name='Активная подписка'),
        ),
        migrations.AlterField(
            model_name='users',
            name='master_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.masterinfo'),
        ),
        migrations.AlterField(
            model_name='users',
            name='settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usersettings'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='color_theme',
            field=models.CharField(default='LIGHT', max_length=255, verbose_name='Цветовая тема'),
        ),
    ]
