# Generated by Django 4.0 on 2023-03-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_users_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterinfo',
            name='uuid',
            field=models.PositiveIntegerField(default=0, verbose_name='UUID'),
        ),
    ]
