# Generated by Django 4.0 on 2023-03-30 02:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_masterinfo_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('code', models.PositiveIntegerField(unique=True, verbose_name='Код')),
                ('expiration_time', models.DateTimeField(default=datetime.datetime(2023, 3, 30, 2, 49, 57, 688616, tzinfo=utc), editable=False, verbose_name='Время истечения')),
            ],
            options={
                'verbose_name': 'Код для проверки',
                'verbose_name_plural': 'Коды для проверки',
            },
        ),
        migrations.AlterField(
            model_name='masterinfo',
            name='uuid',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='UUID'),
        ),
    ]
