# Generated by Django 4.0 on 2023-04-03 02:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_verificationcodes_alter_masterinfo_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcodes',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 2, 37, 53, 764301, tzinfo=utc), editable=False, verbose_name='Время истечения'),
        ),
    ]
