# Generated by Django 4.0 on 2023-04-16 04:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_locations_options_alter_locations_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcodes',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 16, 4, 16, 36, 890555, tzinfo=utc), editable=False, verbose_name='Время истечения'),
        ),
    ]
