# Generated by Django 4.0 on 2023-04-08 06:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_locations_options_alter_locations_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterinfo',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.locations', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='verificationcodes',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 6, 49, 23, 700128, tzinfo=utc), editable=False, verbose_name='Время истечения'),
        ),
    ]
