# Generated by Django 4.0 on 2023-04-08 06:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_masterinfo_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterinfo',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.locations', verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verificationcodes',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 6, 50, 57, 560359, tzinfo=utc), editable=False, verbose_name='Время истечения'),
        ),
    ]
