# Generated by Django 4.0 on 2023-04-08 07:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_masterinfo_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterinfo',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.locations', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='verificationcodes',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 8, 0, 49, 504326, tzinfo=utc), editable=False, verbose_name='Время истечения'),
        ),
    ]
