# Generated by Django 4.0 on 2023-04-18 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('type', models.CharField(choices=[('TRIAL', 'trial')], max_length=255, unique=True, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='ActiveSubscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Дата начала')),
                ('end', models.DateTimeField(verbose_name='Дата окончания')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptions', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Активная подписка',
                'verbose_name_plural': 'Активные подписки',
            },
        ),
    ]
