# Generated by Django 4.0 on 2023-04-27 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_without_discount', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('price_with_discount', models.PositiveIntegerField(verbose_name='Стоимость со скидкой')),
                ('discount_in_percent', models.PositiveIntegerField(verbose_name='Скидка в процентах')),
                ('type', models.CharField(choices=[('TRIAL', 'Trial'), ('PRO', 'Pro')], max_length=255, unique=True, verbose_name='Тип')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('duration_in_days', models.PositiveIntegerField(verbose_name='Продолжительность в днях')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='MastersSubscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('EXPIRED', 'Expired'), ('PAID', 'Paid'), ('ACTIVE', 'Active')], max_length=10, verbose_name='Статус')),
                ('paying_price', models.PositiveIntegerField(default=0, verbose_name='Стоимость в момент оплаты')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.masterinfo', verbose_name='Мастер')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptions', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Подписка мастера',
                'verbose_name_plural': 'Подписки мастеров',
            },
        ),
    ]
