# Generated by Django 4.0 on 2023-03-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='type',
            field=models.CharField(choices=[('TRIAL', 'trial')], max_length=255, unique=True, verbose_name='Тип'),
        ),
    ]
