# Generated by Django 4.0 on 2023-07-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='price_without_discount',
            field=models.PositiveIntegerField(verbose_name='Стоимость без скидки'),
        ),
    ]
