# Generated by Django 4.0 on 2023-04-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='discount_in_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка в процентах'),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='price_with_discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость со скидкой'),
        ),
    ]
