# Generated by Django 4.0 on 2023-04-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptions_discount_in_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='discount_in_percent',
            field=models.PositiveIntegerField(verbose_name='Скидка в процентах'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='price_with_discount',
            field=models.PositiveIntegerField(verbose_name='Стоимость со скидкой'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='type',
            field=models.CharField(choices=[('TRIAL', 'trial'), ('MORE', 'расширенная')], max_length=255, unique=True, verbose_name='Тип'),
        ),
    ]
