# Generated by Django 4.0 on 2023-04-21 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscriptions_discount_in_percent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='price',
            new_name='price_without_discount',
        ),
    ]
