# Generated by Django 4.0 on 2023-04-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_rename_activesubscriptions_masterssubscriptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterssubscriptions',
            options={'verbose_name': 'Подписка мастера', 'verbose_name_plural': 'Подписки мастеров'},
        ),
        migrations.AddField(
            model_name='masterssubscriptions',
            name='status',
            field=models.CharField(choices=[('EX', 'Expired'), ('PAID', 'Paid'), ('ACT', 'Active')], default='EX', max_length=10),
            preserve_default=False,
        ),
    ]
