# Generated by Django 4.0 on 2023-04-21 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_masterinfo_active_subscription'),
        ('subscriptions', '0006_alter_masterssubscriptions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterssubscriptions',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.masterinfo', verbose_name='Мастер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='masterssubscriptions',
            name='end',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='masterssubscriptions',
            name='start',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='masterssubscriptions',
            name='status',
            field=models.CharField(choices=[('EX', 'Expired'), ('PAID', 'Paid'), ('ACT', 'Active')], max_length=10, verbose_name='Статус'),
        ),
    ]
