# Generated by Django 4.0 on 2023-04-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_masterssubscriptions_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='type',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('PRO', 'Pro')], max_length=255, unique=True, verbose_name='Тип'),
        ),
    ]
