# Generated by Django 4.0 on 2023-04-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_subscriptions_image_alter_subscriptions_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterssubscriptions',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='masterssubscriptions',
            old_name='start',
            new_name='start_date',
        ),
    ]
