# Generated by Django 4.0 on 2023-04-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_rename_end_masterssubscriptions_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterssubscriptions',
            name='paying_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость в момент оплаты'),
        ),
        migrations.AlterField(
            model_name='masterssubscriptions',
            name='status',
            field=models.CharField(choices=[('EXPIRED', 'Expired'), ('PAID', 'Paid'), ('ACTIVE', 'Active')], max_length=10, verbose_name='Статус'),
        ),
    ]
