# Generated by Django 4.0 on 2023-04-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_masterssubscriptions_paying_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='description',
            field=models.TextField(default='asd', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='duration_in_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Продолжительность в днях'),
            preserve_default=False,
        ),
    ]
