# Generated by Django 4.0 on 2023-03-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('code', models.PositiveIntegerField(unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Код для проверки',
                'verbose_name_plural': 'Коды для проверки',
            },
        ),
    ]
