# Generated by Django 4.0 on 2023-03-26 04:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcodes',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 4, 37, 23, 186349, tzinfo=utc), editable=False, verbose_name='Время истечения'),
        ),
    ]
