# Generated by Django 4.0 on 2023-03-29 16:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_verificationcodes_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcodes',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 16, 23, 26, 136647, tzinfo=utc), editable=False, verbose_name='Время истечения'),
        ),
    ]
