# Generated by Django 4.0 on 2023-07-07 04:14

from django.db import migrations, models
import verification.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('code', models.PositiveIntegerField(unique=True, verbose_name='Код')),
                ('expiration_time', models.DateTimeField(default=verification.models.get_code_expiration_time, editable=False, verbose_name='Время истечения')),
            ],
            options={
                'verbose_name': 'Код для проверки',
                'verbose_name_plural': 'Коды для проверки',
            },
        ),
    ]
