# Generated by Django 4.0 on 2023-07-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('token', models.CharField(max_length=500, unique=True, verbose_name='Token')),
            ],
            options={
                'verbose_name': 'Токен проверки',
                'verbose_name_plural': 'Токены для проверки',
            },
        ),
    ]
