# Generated by Django 4.0 on 2023-03-23 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_usersimages'),
        ('tokens', '0002_alter_refreshtokens_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtokens',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='Пользователь'),
        ),
    ]
