# Generated by Django 4.0 on 2023-03-12 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_masterinfo_users_master_info'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='master',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.masterinfo'),
        ),
    ]
