# Generated by Django 4.0 on 2023-04-18 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='master',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.masterinfo'),
        ),
        migrations.AddField(
            model_name='serviceimages',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.services', verbose_name='Услуга'),
        ),
    ]
