# Generated by Django 4.0 on 2023-04-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.TextField(default='asd', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='duration_in_minutes',
            field=models.PositiveIntegerField(default=1, verbose_name='Diration in minutes'),
            preserve_default=False,
        ),
    ]
