# Generated by Django 4.0 on 2023-07-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_services_image_alter_services_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specializations',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='specializations',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
