# Generated by Django 4.0 on 2023-05-03 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceRecords',
        ),
    ]
