# Generated by Django 4.0 on 2023-06-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0003_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='client_comment',
            field=models.TextField(default='asd', verbose_name='Client comment'),
            preserve_default=False,
        ),
    ]
