# Generated by Django 4.0 on 2023-07-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0006_unregisteredclientsbookings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unregisteredclientsbookings',
            options={'verbose_name': 'Unregistered clients booking', 'verbose_name_plural': 'Unregistered clients bookings'},
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='client_comment',
        ),
        migrations.RemoveField(
            model_name='unregisteredclientsbookings',
            name='client_comment',
        ),
        migrations.AddField(
            model_name='bookings',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='unregisteredclientsbookings',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
    ]
